- pom.xml
- src/it/compile-fork-it/pom.xml
- src/it/compile-it/pom.xml
- src/it/settings.xml
- src/it/verify-it/pom.xml
> Tidy up invoker based tests

- src/it/bad-bundle/invoker.properties
- src/it/bad-bundle/pom.xml
- src/main/java/org/jenkinsci/maven/plugins/hpi/BundlePluginsMojo.java
> Make hpi:bundle-plugins fail if you forgot the <type> tag

- src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
I tried to add a test, but I run into problems and none of the existing tests run to up to the package phase, so I could not copy/extend a test.
> [JENKINS-28408] fixed support for jpi packaging type

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
[JENKINS-30067](https://issues.jenkins-ci.org/browse/JENKINS-30067)
Not in any of the jars under WEB-INF/lib causing delays.
@reviewbybees
> [JENKINS-30067] Only lookup annotations under classes/*

- src/main/java/org/jenkinsci/maven/plugins/hpi/BundlePluginsMojo.java
Introduced by @stephenc in #15, not yet released.
@reviewbybees
> Fixing typo

- hpi-archetype/pom.xml
[JENKINS-32493](https://issues.jenkins-ci.org/browse/JENKINS-32493)
@reviewbybees
> [JENKINS-32493] Adapt to new plugin parent POM

- src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
See [JENKINS-34496](https://issues.jenkins-ci.org/browse/JENKINS-34496)
@jenkinsci/code-reviewers (esp @jglick)
> [FIX JENKINS-34496] maven-hpi-plugin injecting test for non hpi packged projects

- hpi-archetype/pom.xml
Plus a couple of other minor changes.
@reviewbybees (esp. @daniel-beck )
> Pick up parent POM 2.11

- src/it/assemble-dependencies-as-jpi/invoker.properties
- src/it/assemble-dependencies-as-jpi/pom.xml
- src/it/assemble-dependencies-as-jpi/verify.groovy
- src/it/assemble-dependencies/invoker.properties
- src/it/assemble-dependencies/pom.xml
- src/it/assemble-dependencies/verify.groovy
- src/main/java/org/jenkinsci/maven/plugins/hpi/AssembleDependenciesMojo.java
https://issues.jenkins-ci.org/browse/JENKINS-36876
@reviewbybees @jenkinsci/code-reviewers
> [JENKINS-36876] Add an option to assemble dependencies as jpi files

- src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Supporting change for https://github.com/jenkinsci/jenkins-test-harness/pull/29
@reviewbybees @jenkinsci/code-reviewers (esp @jglick @tfennelly)
See [JENKINS-34496](https://issues.jenkins-ci.org/browse/JENKINS-34496)
> [JENKINS-34496] Fix the injection of tests

- hpi-archetype/src/main/java/HelloWorldBuilder.java
- hpi-archetype/src/main/resources/HelloWorldBuilder/help-useFrench.html
- src/it/compile-fork-it/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
- src/it/compile-it/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
- src/it/process-jar/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
- src/it/verify-it/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/BundlePluginsMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/CreateMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/JarMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/PropertyUtils.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/VersionNumber.java
> Fix the javadoc 8 errors in doctags

- README.md
- src/it/parent-2x/invoker.properties
- src/it/parent-2x/pom.xml
- src/it/parent-2x/src/main/java/test/SampleRootAction.java
- src/it/parent-2x/src/main/resources/index.jelly
- src/it/parent-2x/src/test/java/test/SampleRootActionTest.java
- src/it/parent-2x/src/test/resources/test/expected.txt
- src/it/parent-2x/verify.groovy
> Adding first integration test of 2.x parent POM

- hpi-archetype/pom.xml
> Miscellaneous updates

- src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
Just noticed that using hpi:hpl
@reviewbybees
> Add missing space in error message

- src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
> Escape > as well as < in HTML for compatibility with JDK 8

- Jenkinsfile
- src/site/apt/index.apt
Adds a link to all the plugins goals.
@reviewbybees
> [JENKINS-37619] Add link to all the plugin goals

- README.md
- src/it/jitpack/invoker.properties
- src/it/jitpack/pom.xml
- src/it/parent-2x/invoker.properties
- src/it/parent-2x/pom.xml
Downstream of https://github.com/jenkinsci/plugin-pom/pull/61.
@reviewbybees
> Testing newest plugin POM

- pom.xml
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Note the version bump to 2.0 as it's now Java 8 required.
I upgraded few versions in the pom as well.
> upgrade to Jetty 9.4.5.v20170502

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Fixes [JENKINS-46845](https://issues.jenkins-ci.org/browse/JENKINS-46845)
@reviewbybees
> [JENKINS-46845] Use the webAppFile parameter

- src/it/snapshot-version-override/invoker.properties
- src/it/snapshot-version-override/pom.xml
- src/it/snapshot-version-override/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
- src/it/snapshot-version-override/src/main/resources/index.jelly
- src/it/snapshot-version-override/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/config.jelly
- src/it/snapshot-version-override/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/global.jelly
- src/it/snapshot-version-override/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/help-name.html
- src/it/snapshot-version-override/src/main/resources/org/jenkinsci/tools/hpi/its/Messages.properties
- src/it/snapshot-version-override/src/main/webapp/help-globalConfig.html
- src/it/snapshot-version-override/verify.groovy
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
See [JENKINS-51264](https://issues.jenkins-ci.org/browse/JENKINS-51264)
> [FIXED JENKINS-51264] Add a snapshotPluginVersionOverride configuration option to hpi and hpl goals

- src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Corresponding jira issue:
https://issues.jenkins-ci.org/browse/JENKINS-54949
> parameter to add this plugin to custom war

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
[JENKINS-54807](https://issues.jenkins-ci.org/browse/JENKINS-54807)
With this, it is possible to use the PlatformClassLoader if we are running the plugin
from a Java 9+ JVM.
> [JENKINS-54807] Use PlatformClassLoader if available in the JVM

- README.md
Just a minor documentation patch
> Move changelog to GitHub Releases

- pom.xml
Just a quick patch to get the release flow running
> Use Maven release plugin 2.5.3 to enable releases on Windows

- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Proposed in [JENKINS-53957](https://issues.jenkins-ci.org/browse/JENKINS-53957).
> [JENKINS-53957] Note in the build log when JARs are being bundled, and why

- LICENSE
Supersedes https://github.com/jenkinsci/maven-hpi-plugin/pull/138
> Add an explicit Apache License v2 to the repository

- src/site/site.xml
> Cleanup hyperlinks on the github.io site, remove the DEV@Cloud reference

- src/it/JENKINS-45740-metadata/pom.xml
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
> Fix typo in change log hpi property

- src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
[JENKINS-61937](https://issues.jenkins-ci.org/browse/JENKINS-61937)
No idea how to test this. Thoughts?
> [JENKINS-61937] Safely handle missing dependencies when checking for plugin

- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Helped develop https://github.com/jenkinsci/ldap-plugin/pull/49/commits/74a81d61336b7ae1535350640740083ea5923787.
> Add debug info about which artifact trails were considered

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
> Fix javadoc as consoleForceReload is enabled per default

- src/it/JENKINS-64408-packaged-webresources/invoker.properties
- src/it/JENKINS-64408-packaged-webresources/pom.xml
- src/it/JENKINS-64408-packaged-webresources/src/main/resources/index.jelly
- src/it/JENKINS-64408-packaged-webresources/verify.groovy
This adds a test for packaging webresources with `targetPath` property.
follow up for #208
> add test for packaging webresources

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
See https://github.com/jenkinsci/jenkins/pull/5720.
> Remove references to `DNSMultiCast.disabled`

- pom.xml
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractDependencyGraphTraversingMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/JarMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
I got a little further than #23, although `hpi:run` still isn't working. I could use some help debugging that. I did not bother trying to get `BundlePluginsMojo` to compile, hence this PR being downstream of #246.
> Maven 3 upgrade

- pom.xml
https://github.com/jenkinsci/maven-hpi-plugin/pull/310#discussion_r832210067
> Fixup to #310: remove `icu4j` dep

- Jenkinsfile
> Run tests on Java 8 and 11

- pom.xml
- src/site/apt/index.apt
- src/site/site.xml
Removes unneeded dependencies, updates the skin to the latest version, and does some light copy-editing.
> Update docs site

- src/it/JENKINS-45740-metadata/pom.xml
- src/it/JENKINS-58771-packaged-plugins-2/pom.xml
- src/it/JENKINS-58771-packaged-plugins/pom.xml
- src/it/check-core-version-failure/pom.xml
- src/it/check-core-version-success/pom.xml
- src/it/compile-fork-it/pom.xml
- src/it/compile-it/pom.xml
- src/it/compile-multimodule-it/pom.xml
- src/it/missing-index/pom.xml
- src/it/process-jar/pom.xml
- src/it/snapshot-version-override/pom.xml
- src/it/verify-it/pom.xml
Adapts to [4.40](https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.40).
> Upgrade plugin toolchain in tests

- src/it/assemble-dependencies-as-jpi/pom.xml
- src/it/assemble-dependencies/pom.xml
For some reason these tests were missing their plugin parent POM.
> Add missing plugin parent POM to tests

- src/it/java-level/invoker.properties
- src/it/java-level/pom.xml
- src/it/java-level/src/main/java/org/jenkinsci/tools/hpi/its/X.java
- src/it/java-level/src/main/resources/index.jelly
- src/it/java-level/verify.groovy
Add a test that ensures we print a warning when `java.level` is set.
> Add test for `java.level` warning

- src/it/warResources/invoker.properties
- src/it/warResources/pom.xml
- src/it/warResources/src/main/java/org/jenkinsci/tools/hpi/its/HelloWorldBuilder.java
- src/it/warResources/src/main/resources/index.jelly
- src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/config.jelly
- src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/global.jelly
- src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/HelloWorldBuilder/help-name.html
- src/it/warResources/src/main/resources/org/jenkinsci/tools/hpi/its/Messages.properties
- src/it/warResources/src/main/webResource-filtering/help-globalConfig.html
- src/it/warResources/verify.groovy
IT in preparation for updating filtering code.
> integration test for extra warResources

- src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
See [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658). Before this PR, `mvn -Dset.changelist process-test-classes` in `pipeline-model-definition-plugin` at tag `2.2123.va_31cb_3b_80ef8` failed. After this PR, it succeeds. There is no risk of regression here because this case previously threw an exception, so it can't get any worse than this. If you, the reader, feel there is some way this code could be improved, I would encourage you to file a pull request improving it.
> [JENKINS-62658] Multi-module Jenkins plugins fail `mvn process-test-classes`

- src/it/process-test-classes/invoker.properties
- src/it/process-test-classes/pom.xml
- src/it/process-test-classes/process-test-classes-bar/pom.xml
- src/it/process-test-classes/process-test-classes-bar/src/main/resources/index.jelly
- src/it/process-test-classes/process-test-classes-foo/pom.xml
- src/it/process-test-classes/process-test-classes-foo/src/main/java/HelloWorld.java
- src/it/process-test-classes/process-test-classes-foo/src/main/resources/index.jelly
- src/it/process-test-classes/verify.groovy
The fix for [JENKINS-62658](https://issues.jenkins.io/browse/JENKINS-62658) in #453 deserved a test but I was rushing too fast to write one. Here I go back and improve testing hygiene to preserve this component's maintainability. I ensured that this test failed without the code I recently added for JENKINS-62658. It passes on the main branch.
> Add test for JENKINS-62658

- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
> remove dead code

- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Fixes #493. Also resolves a TODO from 10 years ago. Reference:
https://github.com/apache/maven/blob/29c0a95b0bd105380bb749abfc1a3b188a347005/maven-core/src/main/java/org/apache/maven/plugin/internal/ReadOnlyPluginParametersValidator.java
Reproduced the problem as described in #493 before this PR. Was no longer able to reproduce after this PR.
> Satisfy `ReadOnlyPluginParametersValidator`

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Some of the most disgusting code in this repository (copied from Spotless), but I cannot think of a better way to do this.
Ran `mvn hpi:run` in `text-finder` before and after this PR with Java 17 and a Pipeline job that ran a shell step. Before this PR, got Java module errors; after this PR it worked.
```[tasklist]
```
> [JENKINS-68860] `hpi:run` does not add `Add-Opens` directives for Java 17

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
https://github.com/jenkinsci/winstone/pull/240
Fixes #523
> Add support for WebSocket

- src/it/JENKINS-45740-metadata/pom.xml
- src/it/JENKINS-58771-packaged-plugins-2/pom.xml
- src/it/JENKINS-58771-packaged-plugins-3/pom.xml
- src/it/JENKINS-58771-packaged-plugins/pom.xml
- src/it/assemble-dependencies-as-jpi/pom.xml
- src/it/assemble-dependencies/pom.xml
- src/it/check-core-version-failure/pom.xml
- src/it/check-core-version-success/pom.xml
- src/it/compile-fork-it/pom.xml
- src/it/compile-it/pom.xml
- src/it/compile-multimodule-it/pom.xml
- src/it/java-level/pom.xml
- src/it/jenkins-version/pom.xml
- src/it/metadata-it/pom.xml
- src/it/minimum-java-version/pom.xml
- src/it/missing-index/pom.xml
- src/it/override-test-dependencies-release-failure/pom.xml
- src/it/override-test-dependencies-smokes/pom.xml
- src/it/override-test-dependencies-useUpperBounds/pom.xml
- src/it/override-war-with-snapshot/dependant/pom.xml
- src/it/override-war-with-snapshot/war-with-plugin/pom.xml
- src/it/parent-4x/pom.xml
- src/it/process-jar/pom.xml
- src/it/process-test-classes/pom.xml
- src/it/snapshot-version-override/pom.xml
- src/it/verify-it/pom.xml
- src/it/war-resources/pom.xml
No particular reason to update it now, but the further behind we get, the more problems we tend to run into, so just being proactive.
CI build should be sufficient.
> Update plugin parent POM in test suite

- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
- src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
I am removing this "feature" in https://github.com/jenkinsci/jenkins/pull/8785 and https://github.com/jenkins-infra/jenkins.io/pull/6956.
`mvn clean verify`
> Remove `globalMaskClasses`

- src/it/JENKINS-45740-metadata/pom.xml
- src/it/JENKINS-58771-packaged-plugins-2/pom.xml
- src/it/JENKINS-58771-packaged-plugins-3/pom.xml
- src/it/JENKINS-58771-packaged-plugins/pom.xml
- src/it/assemble-dependencies-as-jpi/pom.xml
- src/it/assemble-dependencies/pom.xml
- src/it/check-core-version-failure/pom.xml
- src/it/check-core-version-success/pom.xml
- src/it/compile-fork-it/pom.xml
- src/it/compile-it/pom.xml
- src/it/compile-multimodule-it/pom.xml
- src/it/ensure-java-level-marker-11-migration/pom.xml
- src/it/ensure-java-level-marker-11/pom.xml
- src/it/java-level/pom.xml
- src/it/jenkins-version/pom.xml
- src/it/metadata-it/pom.xml
- src/it/minimum-java-version/pom.xml
- src/it/missing-index/pom.xml
- src/it/override-test-dependencies-release-failure/pom.xml
- src/it/override-test-dependencies-smokes/pom.xml
- src/it/override-test-dependencies-useUpperBounds/pom.xml
- src/it/override-war-with-snapshot/dependant/pom.xml
- src/it/override-war-with-snapshot/war-with-plugin/pom.xml
- src/it/parent-4x/pom.xml
- src/it/process-jar/pom.xml
- src/it/process-test-classes/pom.xml
- src/it/snapshot-version-override/pom.xml
- src/it/verify-it/pom.xml
- src/it/war-resources/pom.xml
> Update plugin parent POM

- .github/dependabot.yml
https://github.com/jenkinsci/maven-hpi-plugin/pull/586#pullrequestreview-1932982277
> Exclude recent versions of `org.apache.maven.shared:maven-filtering`

- Jenkinsfile
I guess this is how we managed to merge #587 with a failing test. :-\
> Fix a `Jenkinsfile` test result collection bug

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
- src/spotbugs/excludesFilter.xml
Update dependencies in `pom.xml` and adjust imports.
> [JENKINS-73123] Upgrade HPI plugin from Jetty 10.x to 12.x (EE 8)

- .github/dependabot.yml
- pom.xml
Maven 3: `plexus-utils` 4 and `plexus-xml` 3
Maven 4: `plexus-utils` 4 and `plexus-xml` 4
> Clean up `plexus-utils` and `plexus-xml` dependencies

- src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java
https://github.com/jenkinsci/bom/pull/5000#issuecomment-2852005108
Reproduced the problem in `ec2-plugin` with `mvn clean process-test-classes && mvn hpi:resolve-test-dependencies hpi:test-hpl hpi:test-runtime surefire:test` before this PR and https://github.com/jenkinsci/plugin-pom/pull/1138. Could no longer reproduce after this PR.
> Set `jenkins.javaAgent` in `TestRuntimeMojo`

- src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Fixes #565. Amends #178. Compare #746.
> `wildcardLocalhostDNS`
