src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
For consistency with other Maven plugins. NetBeans will recognize it at this location, for example.
@reviewbybees
=> ${basedir}/target/generated-test-sources/injected/

src/it/bundle-fails-optional-conflict/invoker.properties, src/it/bundle-fails-optional-conflict/pom.xml, src/it/bundle-with-optional-deps/invoker.properties, src/it/bundle-with-optional-deps/pom.xml, src/it/bundle-with-optional-deps/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/BundlePluginsMojo.java
*NOTE:* currently Jenkins core does not understand optionally bundled plugins, so either a module or a plugin would need to extract them somehow
@reviewbybees
=> Add the ability to bundle optional plugins separately from regular

hpi-archetype/src/main/java/HelloWorldBuilder.java
See [discussion](https://groups.google.com/d/msg/jenkinsci-dev/0dqXhbjRhYs/AAY6RUn6AgAJ).
With this change, if you create the sample project, `hpi:run` it, and install _Workflow: Aggregator_, _Snippet Generator_ suggests
```groovy
node {
step([$class: 'HelloWorldBuilder', name: 'Bob'])
}
```
(well, without the required `node` context but that is another matter) and this works.
@reviewbybees
=> Implement SimpleBuildStep on sample builder

pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
`hpi:run` should run Jetty 9.2 to support Servlet 3.1.
I've fixed how we track upstream files from jetty-maven-plugin so that future merges like this will be more manageable.
The diff view in this PR mixes upstream changes in Jetty and local changes, which is useless. If you want to really understand the diff, look at `git log -U jetty9.2 '^incoming' '^master'`
@reviewbybees
=> [JENKINS-23378] update to Jetty9.2

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Without this fix,
mvn -f maven-plugin hpi:run
fails with
```
… hudson.PluginManager$1$3$2$1 reactOnCycle
SEVERE: found cycle in plugin dependencies: (root=Plugin:maven-plugin, deactivating all involved) Plugin:maven-plugin -> Plugin:promoted-builds -> Plugin:maven-plugin
```
Same for the problem identified in https://github.com/jenkinsci/junit-plugin/pull/31.
@reviewbybees esp. @andresrc, @emanuelez
=> We must use runtime scope for work/plugins/$p.hpl

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java
- To enable the ability to unbundle bouncycastle we need to be able to target an unreleased Jenkins version as the baseline for a plugin
@jenkinsci/code-reviewers @reviewbybees 
See [JENKINS-36923](https://issues.jenkins-ci.org/browse/JENKINS-36923)
=> [JENKINS-36923] Allow declaring dependency on future release of core

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
While trying to track down what might have gotten broken in a plugin snapshot build, I noticed that the order of `Plugin-Dependencies` was random. Making it deterministic.
(Note that currently the primary sort key is effectively `groupId`, which means that from the perspective of plugin `shortName`s the list is not lexicographically sorted, though it _is_ deterministic.)
@reviewbybees
=> Sort artifacts so that Plugin-Dependencies appears in a consistent order from build to build

src/it/jitpack/invoker.properties, src/it/jitpack/pom.xml, src/it/jitpack/src/main/java/test/C.java, src/it/jitpack/src/main/resources/index.jelly, src/it/jitpack/src/test/java/test/CTest.java, src/it/jitpack/verify.groovy, src/it/settings.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Ignoring the GAV used to express the dependency. Seems to fix a problem in the contents of `Plugin-Dependencies` in `target/test-classes/the.hpl` and `target/*.hpi` when using jitpack.io as in https://github.com/jenkinsci/plugin-pom/pull/37.
Possibly other uses of dependency GAVs are also wrong, say in the `run` goal (?), but this is the one I noticed for now.
@reviewbybees
=> Parse Short-Name & Plugin-Version out of the actual plugin manifest

Jenkinsfile
@reviewbybees esp. @rtyler who should please create a ci.jenkins.io job for this, to replace [`Libraries/maven-hpi-plugin`](https://ci.jenkins.io/job/Libraries/job/maven-hpi-plugin/) using the Evil Job Type.
Once there is a home, the *Build Status* link in `README.md` could be updated (or just deleted—we expect `master` to always be a blue ball, right?).
=> New Jenkinsfile

src/it/jitpack/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
=> More fixes to mojos that assumed that plugin artifacts used a short name identical to the artifactId

src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Running many plugin builds in parallel makes identifying failing ones with the current JUnit plugin a pain. This additional log aims at mitigating this a bit waiting for an actual JUnit plugin improvement to subcategorize Jenkins JUnit reporting.
Add the following first line to the `InjectedTest-output.txt` file:
```
Running tests for com.company.group:someplugin:1.2.3-SNAPSHOT
```
@reviewbybees
=> Add log for current artifact under test

pom.xml
#62 broke the build. I do not know why, exactly; something to do with a Velocity upgrade. I cannot find the file mentioned anywhere. Anyway, should not have been merged until that was corrected, so here it is belatedly so that other PRs do not get marked as failures.
@reviewbybees
=> Fixing site generation

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/resources/META-INF/plexus/components.xml
[JENKINS-24064](https://issues.jenkins-ci.org/browse/JENKINS-24064)
Should allow us to avoid deploying two copies of `jenkins.war`, while simplifying how `WarExploder` finds the WAR file to use.
@reviewbybees
=> [JENKINS-24064] Replace war-for-test classifier with executable-war type

src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Compilability is verified by existing ITs; I did not bother adding an assertion that there are no compiler warnings in the log since this is pretty trivial.
@reviewbybees
=> Fixing unchecked/rawtypes warnings in InjectedTest

src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Various bugs. For example, `mvn -f artifact-manager-s3 hpi:run` was producing nonsense like
```
[WARNING] will not overwrite …/artifact-manager-s3-plugin/work/plugins/null.jpi with …/.m2/repository/org/jenkins-ci/ui/handlebars/1.1.1/handlebars-1.1.1.hpi because it is newer
```
First of all, this was not a plugin dependency; there was a dependency on `handlebars-1.1.1-core-assets.jar` via `jenkins-war`, not on `handlebars-1.1.1.hpi`. (Similarly, `test`-scoped dependencies on `*-tests.jar` were messing things up.) Second, the mojo was copying into a file `null.jpi`, which wreaked havoc later.
The warning was also inappropriate even in cases where the data was correct—nothing is broken here, just a working home with some plugin updates—and failed to specify the newer version.
=> Fixing RunMojo dependency copy logic

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Otherwise you can get your work dir polluted by old `*.jpl` links which you would need to clean up manually after switching back to a release version for a test dep.
=> Delete work/plugins/*.jpl where the current test-scoped dependency is not in fact a snapshot

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
Otherwise in conjunction with https://github.com/jenkinsci/plugin-pom/pull/122 I have seen
```
[INFO] Tmp directory = …-plugin/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] jetty-9.4.5.v20170502
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@3749e682{/jenkins,null,UNAVAILABLE}{…/.m2/repository/org/jenkins-ci/main/jenkins-war/2.138.2/jenkins-war-2.138.2.war}
java.lang.IllegalStateException: Failed to delete temp dir …-plugin/target/tmp
at org.eclipse.jetty.webapp.WebInfConfiguration.configureTempDirectory (WebInfConfiguration.java:376)
at org.eclipse.jetty.webapp.WebInfConfiguration.resolveTempDirectory (WebInfConfiguration.java:264)
at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure …
```
=> Use a more specific temp dir for Jetty

pom.xml, src/it/parent-3x/invoker.properties, src/it/parent-3x/src/main/java/test/JustTesting.java, src/it/parent-3x/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Corrects a regression in #75, noticed in https://github.com/jenkinsci/external-monitor-job-plugin/pull/18.
=> Pass minimumJavaVersion to RunMojo so that hpi:run works again

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
To simplify plugin POMs, especially after https://github.com/jenkinsci/plugin-pom/pull/134 (no need for a `plugin-pom` patch).
=> Permitting ${hpi.compatibleSinceVersion} to be used to configure mojos rather than a <plugin> section

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
E.g. https://github.com/kubernetes-client/java/pull/334#issuecomment-475674883. Maven already prints a warning about such dependencies when computing the set of artifacts, as does the Enforcer plugin, so this is just preventing later phases from breaking the build.
=> A ProjectBuildingException on some dependency should not be fatal

pom.xml
I would like to update to Maven 3.5 later to keep it aligned with Plugin POM, but such change should at least help with dependency management a bit
=> Align versions of Maven and Maven Plugin Tools dependencies

src/it/JENKINS-58771-packaged-plugins/invoker.properties, src/it/JENKINS-58771-packaged-plugins/pom.xml, src/it/JENKINS-58771-packaged-plugins/src/main/resources/index.jelly, src/it/JENKINS-58771-packaged-plugins/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
[JENKINS-58771](https://issues.jenkins-ci.org/browse/JENKINS-58771)
Plugin artifacts are determined only from project artifacts, which captures only dependencies with compile/runtime scopes.
In some cases, it can happen that transitive dependencies are resolved via a test-scoped trail, causing unexpected dependencies to be packaged in the resulting hpi.
=> [JENKINS-58771] Consider plugin dependencies with test scope to consider whether bundling a dependency is needed

Jenkinsfile, pom.xml, src/it/JENKINS-45740-metadata/invoker.properties, src/it/JENKINS-58771-packaged-plugins/invoker.properties, src/it/assemble-dependencies-as-jpi/invoker.properties, src/it/assemble-dependencies/invoker.properties, src/it/bad-bundle/invoker.properties, src/it/bundle-fails-optional-conflict/invoker.properties, src/it/bundle-with-optional-deps/invoker.properties, src/it/compile-fork-it/invoker.properties, src/it/compile-it/invoker.properties, src/it/parent-3x/invoker.properties, src/it/process-jar/invoker.properties, src/it/snapshot-version-override/invoker.properties, src/it/verify-it/invoker.properties
Found it cumbersome to track down the error in #150 so wanted to modernize a bit. With `-ntp` it is reasonable to stream IT logs to the main build log.
=> CI improvements

pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Supersedes #150. Picking up the sort of no-op servlet security realm that `JenkinsRule` uses. Confirmed that this works with the `build-token-root` plugin with authentication enabled (`initialAdminPassword` style).
=> Upgrade Jetty from 9.4.5.v20170502 to 9.4.22.v20191022

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Local development setups usually don't need to listen on all interfaces, so restrict to `localhost` by default.
Apparently `host` is the Jetty terminology for the listen address, so use that here.
I didn't want to think about IPv4/IPv6, so use `localhost` instead of e.g. `127.0.0.1`. `JenkinsRule` uses `localhost` as well.
Restore previous behavior by setting `-Dhost=0.0.0.0` on the command line.
Corresponding PR in core at https://github.com/jenkinsci/jenkins/pull/4515.
=> Listen on loopback interface by default

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java
When I use `hpi:run` in a project, I see something like this:
```
[INFO] Tmp directory = /tmp/jenkinsci/workflow-basic-steps-plugin/target/jetty
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
```
There are two spaces between `=` and `none` for no apparent reason.
This change replaces the second space followed by a _default_message_ with `(`+_default_message_+`)`.
=> Improve debugging formatting

src/it/JENKINS-58771-packaged-plugins-2/invoker.properties, src/it/JENKINS-58771-packaged-plugins-2/pom.xml, src/it/JENKINS-58771-packaged-plugins-2/src/main/resources/index.jelly, src/it/JENKINS-58771-packaged-plugins-2/verify.groovy, src/it/JENKINS-58771-packaged-plugins-3/invoker.properties, src/it/JENKINS-58771-packaged-plugins-3/pom.xml, src/it/JENKINS-58771-packaged-plugins-3/src/main/resources/index.jelly, src/it/JENKINS-58771-packaged-plugins-3/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Expands https://github.com/jenkinsci/maven-hpi-plugin/pull/140
Sometimes some dependencies gets pulled through test or provided scope
trails, because in fact they are being pulled in compile scope through a plugin with a longer trail.
Inspired by https://github.com/jenkinsci/kubernetes-plugin/pull/729
=> [JENKINS-58771] Avoid more cases of bundling libs incorrectly

pom.xml, src/it/parent-3x/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Analogue of https://github.com/jenkinsci/winstone/pull/63. Before:
```
Apr 21, 2020 4:01:24 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
```
After:
```
2020-04-21 20:35:45.911+0000 [id=73]	INFO	hudson.WebAppMain$3#run: Jenkins is fully up and running
```
=> Use SupportLogFormatter from hpi:run

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
When you `hpi:run` from a lot of plugins, each with their own `work` directory, it is annoying to always be using the same `http://localhost:8080/jenkins/` URL: your address bar will get all mixed up, cookies will get crossed over, saved `initialAdminPassword`s will be confused, etc. It is nicer to browse to e.g. `http://build-token-root.127.0.0.1.nip.io:8080/jenkins/` which corresponds to just one `work` directory. This patch just makes it a bit easier to get such a URL.
=> Offer a browse URL from hpi:run including the likes of nip.io if desired

src/main/java/org/jenkinsci/maven/plugins/hpi/ListPluginDependenciesMojo.java
Just noticed a documentation bug while answering a question from @rsvoboda in https://github.com/jenkinsci/jenkinsfile-runner/pull/388#issuecomment-706065413 . Documentation on https://jenkinsci.github.io/maven-hpi-plugin/list-plugin-dependencies-mojo.html is misleading.
Also added a TODO comment to actually add support for listing all plugin dependencies without actual download in https://jenkinsci.github.io/maven-hpi-plugin/assemble-dependencies-mojo.html
=> Fix `list-plugin-dependencies` documentation, not all plugins are listed by the mojo

src/it/check-core-version-failure/pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
=> `validate-hpi` needs test-scope dependency resolution for these plugin dependencies using test scope

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
- it works for the packaging phase out of the box
- for use as part of `hpi:run`, the goals `compile` and `hpi:hpi` must be executed before to ensure that `webappDirectory` exists. otherwise `warSourceDirectory` will be used as before.
**example:** `mvn -DskipTests=true -Dport=8081 clean compile hpi:hpi hpi:run`
Please see [JENKINS-64408](https://issues.jenkins.io/browse/JENKINS-64408) for the background and motivation of this.
=> [JENKINS-64408] support targetPath property for webResources

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
I had a corrupt download and withhout this change I couldn't find what it was, after this I was able to easily find it
=> Log artifactId in validate mojo on IOException

src/it/compile-multimodule-it/invoker.properties, src/it/compile-multimodule-it/plugin1/pom.xml, src/it/compile-multimodule-it/plugin2/pom.xml, src/it/compile-multimodule-it/pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
When running `mvn compile` on a multimodule project containing multiple jenkins plugins depending on each other, build is failing with `Unable to retrieve manifest`.
This is because the current validation requires that a manifest is available and expects a packaged file (required `mvn package` at least).
This is skipping the validation in this particular case, issuing a warning.
=> Fix `mvn compile` in multimodule projects

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
I was puzzled to see (non-incrementalified) plugins labelled e.g. `1.15-SNAPSHOT (private-abcd1234-jglick)` apparently referring to a commit not present in the plugin repository. Finally figured out that these were real commits, in _another_ repository from which I was running e.g.
```bash
mvn -f ../something-plugin -Pquick-build clean package
java -jar jenkins-cli.jar install-plugin = -restart < ../something-plugin/target/something.hpi
```
=> Use the project’s basedir to run `git rev-parse HEAD`

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Fixes an (unreleased) regression introduced in #247.
=> Ensure implementation and specification entries are present in `MANIFEST.MF`

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
@daniel-beck pointed me to this replacement for https://wiki.jenkins.io/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions.
=> Link to `/doc/developer/plugin-development/mark-a-plugin-incompatible/`

pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Addresses this long-standing comment from commit commit ee161c7:
> All I want to do here is to invoke the hpl target. there must be a better way to do this!
> jglick: perhaps https://github.com/TimMoore/mojo-executor would work?
Indeed, it would.
=> Use `mojo-executor`

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RecordCoreLocationMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
Fixes the following build warnings:
```
[WARNING] Deprecated @Component annotation for 'project' field in org.jenkinsci.maven.plugins.hpi.RunMojo: replace with @Parameter( defaultValue = "${project}", readonly = true )
[WARNING] Deprecated @Component annotation for 'project' field in org.jenkinsci.maven.plugins.hpi.RecordCoreLocationMojo: replace with @Parameter( defaultValue = "${project}", readonly = true )
[WARNING] Deprecated @Component annotation for 'project' field in org.jenkinsci.maven.plugins.hpi.TestDependencyMojo: replace with @Parameter( defaultValue = "${project}", readonly = true )
[WARNING] Deprecated @Component annotation for 'project' field in org.jenkinsci.maven.plugins.hpi.HplMojo: replace with @Parameter( defaultValue = "${project}", readonly = true )
[WARNING] …
```
=> Fix deprecated `@Component` annotation warnings

.github/dependabot.yml
Should avoid the likes of #288. Matches
https://github.com/jenkinsci/jenkins/blob/f0089728741e3ebbf752f938b8bbd16d1e492b24/.github/dependabot.yml#L37-L39
=> Ignore Jetty 10.x and 11.x

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
The fewer third-party dependencies we have, the easier maintenance becomes. This PR removes usages of the third-party `StringUtils` class in favor of native Java Platform functionality.
=> Remove usages of `StringUtils`

src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
Noticed while doing end-to-end testing of jenkinsci/jenkins#5979.
Build the latest version of `jnr-posix-api`, install it, then go to **Configure Global Security**. Select **Unix user/group database** and click **Test**.
The test should pass.
The test fails with:
<details>
<summary>Stack trace</summary>
<pre>
Failed to load native POSIX impl; falling back on Java impl. Stacktrace follows.
java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:49)
at jnr.ffi.LibraryLoader.load(LibraryLoader.java:418)
at jnr.posix.POSIXFactory$DefaultLibCProvider$SingletonHolder.<clinit>(POSIXFactory.java:307)
at jnr.posix.POSIXFactory$DefaultLibCProvider.getLibC(POSIXFactory.java:335)
at …
=> Include classifier when computing final name

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
Fixes the following SpotBugs violation:
```
[ERROR] Medium: org.jenkinsci.maven.plugins.hpi.ValidateHpiMojo.getDependencyCoreVersion(MavenArtifact) may fail to close stream [org.jenkinsci.maven.plugins.hpi.ValidateHpiMojo] At ValidateHpiMojo.java:[line 48] OS_OPEN_STREAM
```
=> Fix `OS_OPEN_STREAM` SpotBugs violation

src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Fixes the following SpotBugs violation:
```
[ERROR] Medium: Check to see if return value of org.apache.maven.artifact.versioning.ArtifactVersion.compareTo(Object) is equal to -1 [org.jenkinsci.maven.plugins.hpi.TestInsertionMojo] At TestInsertionMojo.java:[line 77] RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUE
```
=> Fix `RV_CHECK_COMPARETO_FOR_SPECIFIC_RETURN_VALUE` SpotBugs violation

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestHplMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojo.java
Fixes the following SpotBugs violations:
```
[ERROR] Medium: Exceptional return value of java.io.File.mkdirs() ignored in org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo.buildExplodedWebapp(File, File) [org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo, org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo, org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo] At AbstractHpiMojo.java:[line 337]Another occurrence at AbstractHpiMojo.java:[line 340]Another occurrence at AbstractHpiMojo.java:[line 343] RV_RETURN_VALUE_IGNORED_BAD_PRACTICE
[ERROR] Medium: Exceptional return value of java.io.File.mkdirs() ignored in org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo.copyDependentWarContents(File, File) [org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo, org.jenkinsci.maven.plugins.hpi.AbstractHpiMojo] At …
```
=> Fix `RV_RETURN_VALUE_IGNORED_BAD_PRACTICE` SpotBugs violations

Jenkinsfile, pom.xml, src/it/JENKINS-45740-metadata/invoker.properties, src/it/JENKINS-58771-packaged-plugins-2/invoker.properties, src/it/JENKINS-58771-packaged-plugins-3/invoker.properties, src/it/JENKINS-58771-packaged-plugins/invoker.properties, src/it/assemble-dependencies-as-jpi/invoker.properties, src/it/assemble-dependencies/invoker.properties, src/it/check-core-version-failure/invoker.properties, src/it/check-core-version-success/invoker.properties, src/it/compile-fork-it/invoker.properties, src/it/compile-it/invoker.properties, src/it/compile-multimodule-it/invoker.properties, src/it/parent-3x/invoker.properties, src/it/process-jar/invoker.properties, src/it/snapshot-version-override/invoker.properties, src/it/verify-it/invoker.properties
Inspired by a change in https://github.com/jenkinsci/plugin-pom/pull/508. Rather than streaming all the IT logs to the Jenkins build log, capture them in JUnit-format test results instead, and treat any failures as an unstable build. Should make it easier to develop #66 and the like.
=> Record `maven-invoker-plugin` failures via `junit` rather than console

pom.xml, src/spotbugs/spotbugs-excludes.xml
Currently, we exclude any medium-threshold SpotBugs violations. This means that existing violations don't trip up the build, but it also means we won't notice if new medium-threshold violations get introduced.
Add an exclude filter file with fine-grained suppressions of specific medium-threshold violations for the classes that currently violate them. This way, the build remains green, but if a new medium-threshold violation gets introduced, we would notice that right away.
=> Fine-grained SpotBugs exclusions

src/it/missing-index/invoker.properties, src/it/missing-index/pom.xml, src/it/missing-index/src/main/java/org/jenkinsci/tools/hpi/its/X.java, src/it/missing-index/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java
See https://github.com/jenkinsci/junit-attachments-plugin/pull/28 for example.
=> Enforce existence of `src/main/resources/index.jelly`

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
As proposed in https://github.com/jenkinsci/maven-hpi-plugin/pull/310#discussion_r832214118, cleaning up some code mostly introduced in #247 or which at least could have been simplified at that time. Creating a `DefaultProjectBuildingRequest` based on the `session.projectBuildingRequest` makes sense if you actually need to override some property. Otherwise it just copies properties from the original. And that means `${localRepository}` and `${project.remoteArtifactRepositories}` should not need to be injected; pick those things up from the `session`.
=> Avoid copying `session.projectBuildingRequest` unless overriding something

pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJettyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TagLibInterfaceGeneratorMojo.java
Fixes the following build warning by placing the dependencies in the `<provided>` scope:
```
[ERROR] 
Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.
The following dependencies are in wrong scope:
* org.apache.maven:maven-model:jar:3.8.5:compile
* org.apache.maven:maven-core:jar:3.8.5:compile
* org.apache.maven:maven-settings:jar:3.8.5:compile
* org.apache.maven:maven-settings-builder:jar:3.8.5:compile
* org.apache.maven:maven-builder-support:jar:3.8.5:compile
* org.apache.maven:maven-repository-metadata:jar:3.8.5:compile
* org.apache.maven:maven-model-builder:jar:3.8.5:compile
* org.apache.maven:maven-resolver-provider:jar:3.8.5:compile
* …
```
=> Some dependencies of Maven Plugins are expected to be in provided scope

src/it/JENKINS-45740-metadata/pom.xml, src/it/JENKINS-58771-packaged-plugins-2/pom.xml, src/it/JENKINS-58771-packaged-plugins-3/pom.xml, src/it/JENKINS-58771-packaged-plugins/pom.xml, src/it/assemble-dependencies-as-jpi/pom.xml, src/it/assemble-dependencies/pom.xml, src/it/check-core-version-failure/pom.xml, src/it/check-core-version-failure/verify.groovy, src/it/check-core-version-success/pom.xml, src/it/compile-fork-it/pom.xml, src/it/compile-it/pom.xml, src/it/compile-multimodule-it/plugin1/pom.xml, src/it/compile-multimodule-it/plugin2/pom.xml, src/it/compile-multimodule-it/pom.xml, src/it/missing-index/pom.xml, src/it/parent-3x/pom.xml, src/it/parent-3x/verify.groovy, src/it/process-jar/pom.xml, src/it/process-jar/verify.groovy, src/it/snapshot-version-override/pom.xml, src/it/verify-it/pom.xml
The tests for this component were using ancient versions of Jenkins core and the plugin parent POM. This PR updates the tests to use relatively recent versions of Jenkins core and the plugin parent POM for more realistic testing.
=> Modernize tests

pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
The validation mojo currently checks for Java 6 or later and Jenkins 1.420 or later. These seem like pretty old minimum requirements.
This PR bumps the minimum supported core version to 2.204 and enforces minimum Java version based on the value encoded by core, at whatever version of core the plugin is running against. The only place this is encoded right now is in `java.level` in `core-bom`, which is where we're reading it (well, `MANIFEST.MF` in `jenkins.war` encodes a `Build-Jdk-Spec`, but that could be problematic if you did a local build with Java 11 and `<release>8</release>`, so I am not relying on it). I don't feel strongly about encoding it in this particular way, just that it is encoded _somewhere_ in the artifacts published by core and that we read it out here. If we want to …
=> Improve validation mojo

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
Tested manually with https://github.com/jenkinsci/plugin-pom/pull/522
=> Print warning if using deprecated `java.level` with new enough parent POM

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java, src/main/resources/META-INF/plexus/components.xml
Currently, people testing with Java 17 must add an awkward `-DargLine=` directive with the `Add-Opens` modules from the core version they are testing. This PR applies a trick to dynamically set this based on the values in `MANIFEST.MF`.
With this in place, anyone with a sufficiently recent core (2.341+), test harness (1721.v385389722736+), and `maven-hpi-plugin` (this PR) should be able to effortlessly do Java 17 testing and indeed enable Java 17 in their `Jenkinsfile`. Once this is merged, I will try to do a release and wrap this and the test harness change into a new plugin POM release so that the requirement just becomes "core 2.341+ and plugin POM 4.40+".
Tested with `workflow-job` and Java 17:
```
$ mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.job.WorkflowJobTest,org.jenkins …
```
=> Dynamically apply `Add-Opens` directives from `MANIFEST.MF`

src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java
Chases away the new warnings inadvertently introduced in #310:
```
[INFO] --- maven-compiler-plugin:3.10.1:testCompile (default-testCompile) @ git-client ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 66 source files to /home/basil/src/jenkinsci/git-client-plugin/target/test-classes
[INFO] 
[INFO] --- maven-hpi-plugin:3.27-SNAPSHOT:test-hpl (default-test-hpl) @ git-client ---
[INFO] Generating /home/basil/src/jenkinsci/git-client-plugin/target/test-classes/the.hpl
[INFO] 
[INFO] --- maven-hpi-plugin:3.27-SNAPSHOT:resolve-test-dependencies (default-resolve-test-dependencies) @ git-client ---
[INFO] 
[INFO] --- gmavenplus-plugin:1.13.1:compileTests (test-in-groovy) @ git-client ---
[INFO] No sources specified for compilation. Skipping.
```
Fixes #325.
=> Skip model validation of resolved POMs

src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java, src/main/resources/META-INF/plexus/components.xml
After writing the `InitializeMojo` I realized that the test-related portions could be split out into their own mojo that runs later, just before we start the tests. This allows us to avoid doing unnecessary work when running with `-DskipTests`.
=> Split test preparation into its own mojo

src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java
Small fixup that goes along with https://github.com/jenkinsci/plugin-pom/pull/530. That PR blanks out the `source` and `target` properties when using `release`, but this code checks just checks for null rather than null or empty. By making this code check for null or empty, the "magic" of `InitializeMojo` now becomes a no-op against current cores on all versions of Java as of https://github.com/jenkinsci/plugin-pom/pull/530, which I believe was the desired result according to reviewers.
=> Treat blank properties as unset

src/it/minimum-java-version/invoker.properties, src/it/minimum-java-version/pom.xml, src/it/minimum-java-version/src/main/java/org/jenkinsci/tools/hpi/its/X.java, src/it/minimum-java-version/src/main/resources/index.jelly, src/it/minimum-java-version/verify.groovy, src/it/process-jar/pom.xml, src/it/verify-it/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Reverts #75. See [the mailing list thread](https://groups.google.com/g/jenkinsci-dev/c/V2CH4pNQitQ/m/ZNmNb0x7BwAJ) along with https://github.com/jenkinsci/jenkins/pull/6549 and https://github.com/jenkins-infra/update-center2/pull/591. This is dead code, so we intend to stop producing it from `maven-hpi-plugin` and to stop consuming it from `jenkins` and `update-center2`. A new integration test verifies that we issue a warning if users are still trying to specify this in their build configuration.
=> Revert JENKINS-20679

src/main/resources/META-INF/plexus/components.xml
Some cleanup. See https://github.com/jenkinsci/jep/pull/391.
=> [JEP-230] Noting deprecation of `jenkins-module` packaging

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
A bug in #336 noticed when doing further testing: we were generating upper bounds overrides of the plugin under test (!), which led to the upper bounds analysis never iterating to convergence. Needless to say we should never be trying to add ourselves to our own dependency management section.
=> Ignore self in upper bounds analysis

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Noticed when testing with the `variant` plugin, which has its own entry for `maven.test.dependency.excludes` for test purposes. Before this PR we were clobbering the existing value of this property; after this PR, we append to it rather than clobbering it. I tested that this gets the `variant` plugin's tests working again (at least after they're converted to use the `maven.test.dependency.excludes` rather than setting the value directly).
=> Append to existing properties rather than clobbering them

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
This gets in the way of PCT's `install` goal specified in this code path:
https://github.com/jenkinsci/plugin-compat-tester/blob/f035412416dd448b85b472c65202ac6a6b7c50ef/plugins-compat-tester/src/main/java/org/jenkins/tools/test/hook/MultiParentCompileHook.java#L124-L130
=> Relax release check

src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java
`maven-hpi-plugin` setting `animal.sniffer.skip` to `true` unconditionally may be exceeding its responsibilities, and making difficult (if not impossible) to actually run animal sniffer in plugins: overriding `animal.sniffer.skip` in a plugin to make it `false` is not taking any effect, it’s still skipped.
Removing this here and only keeping https://github.com/jenkinsci/plugin-pom/blob/283a7c29b3f08b8ffa1ebd51d7d8f9d520447995/pom.xml#L961 has no negative affect on plugins without signature checking, using either java 8 or 11, and allows to enable animal sniffer in plugins to their discretion.
=> re-allow animal sniffer

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Trying to figure out what https://github.com/jenkinsci/maven-hpi-plugin/pull/336#discussion_r860922529 really meant.
(`overrideWar` does not appear to have any IT coverage, so this is just a placeholder to be tested in the context of `bom`.)
=> `resolve-test-dependencies` should not add deps unrelated to the model by default

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
```
[INFO] Updating dependency management entry org.jenkins-ci.plugins:git from 4.10.0 to 4.11.3
[INFO] Updating dependency management entry org.jenkins-ci.plugins:git from 4.10.0 to 4.11.3
```
is confusing.
Amends #336.
=> Indicate `classifier` if set in `updateDependency` message

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Appears to be necessary to run PCT on `warnings-ng` at least in the CloudBees configuration. (Not clear if https://github.com/jenkinsci/bom/pull/1384 even got that far.)
Amends #336.
=> Add a `dependencyManagement` section if missing

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
Happened to me when I create a new plugin, executed `git init`, and then `mvn clean verify`.
When there is no commits, the outcome is just `HEAD` instead of the commit sha. Due to it having a length of 4, the substring fails.
> [ERROR] Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.28:test-hpl (default-test-hpl) on project sudo-mode: Execution default-test-hpl of goal org.jenkins-ci.tools:maven-hpi-plugin:3.28:test-hpl failed: begin 0, end 8, length 4 -> [Help 1]
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
Resolves #303.
=> Consider empty repository situation

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
A variety of plugins use deprecated (e.g. `git://``) or insecure (e.g., `http://`) SCM URLs, or URLs that cause problems for PCT. This PR adds a new (soft) warning that highlights such problems and provides a correction to the user. This shouldn't be very disruptive since I have already filed PRs to update the most egregious violations. I tested this on some of the same changes that I already filed PRs for to confirm that the suggestions match what I actually submitted in the PRs (before authoring this change).
=> Add a warning when using deprecated or insecure SCM URLs

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractDependencyGraphTraversingMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
When building a plugin against a plugin parent POM that is in the same multi-module project, the build fails.
```
$ wget https://raw.githubusercontent.com/jenkinsci/plugin-pom/master/pom.xml
[…]
$ git clone https://github.com/jenkinsci/text-finder-plugin.git             
Cloning into 'text-finder-plugin'...
[…]
$ sed -i -e 's/4.51/4.52-SNAPSHOT/g' text-finder-plugin/pom.xml             
$ sed -i -e '/relativePath/d' text-finder-plugin/pom.xml 
$ sed -i -e 's/<properties>/<modules><module>text-finder-plugin<\/module><\/modules><properties>/g' pom.xml
$ mvn clean verify -DskipTests -e
```
<details>
<summary>Stack trace</summary>
<pre>
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.35:validate (default-validate) on …
=> Support multi-module builds (regression in 3.26)

src/it/parent-4-40/invoker.properties, src/it/parent-4-40/pom.xml, src/it/parent-4-40/src/main/java/test/JustTesting.java, src/it/parent-4-40/src/main/java/test/SampleRootAction.java, src/it/parent-4-40/src/main/resources/index.jelly, src/it/parent-4-40/src/test/java/test/SampleRootActionTest.java, src/it/parent-4-40/src/test/resources/test/expected.txt, src/it/parent-4-40/verify.groovy
A copy of `parent-4x` that verifies that the HPI plugin continues to work against older plugin parent POMs like 4.40.
=> Add new test for older plugin parent POM

src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java, src/main/resources/META-INF/plexus/components.xml
Removing some no-longer-necessary Java 8 logic and maybe hoping to fix jenkinsci/bom#1551 by moving the copying of the patch module to an earlier phase? To test this I ran `mvn clean verify -Dtest=org.jenkinsci.plugins.workflow.libs.LibraryMemoryTest`.
=> Clean up `TestRuntimeMojo`

pom.xml
The plugins Mojos are not defined in dependencies, so do not try and unpack them looking for them
This fixes a slew of warnings when building the plugin on windows: 
```
[WARNING] Archive entry
'org/apache/maven/plugins/dependency/fromDependencies/AbstractFromDependenciesMojo.java' and existing file
'C:\workarea\source\github\jenkinsci\maven-hpi-plugin\target\maven-plugin-plugin-sources\org.apache.maven.plugins\maven-dependency-plugin\3.4.0\sources\org\apache\maven\plugins\dependency\fromDependencies\AbstractFromDependenciesMojo.java' names differ only by case. This may lead to an unexpected outcome on case-insensitive filesystems.
```
This fixes the noise spam.  really the unarchiver that is erroneously warning (the names do match just `/` is a `\`) but I could not quickly find the …
=> do not try and unpack all our dependencies looking for a mojo

Jenkinsfile
Adding windows to the mix as
1. we have developers consuming hpi plugin on windows so we want to run the ITs on windows to ensure we do not break windows plugin development
2. we have developers contributing to this plugin using windows and have observed some windows specific issues in the plugin build.
[build log](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fmaven-hpi-plugin/detail/PR-422/1/pipeline/72#step-85-log-67) demonstrates that #420 was not complete.
=> Add windows to the build

pom.xml
on windows the build would produce a large amount of warnings due to https://github.com/codehaus-plexus/plexus-archiver/issues/248 which in turn caused https://issues.apache.org/jira/browse/MPLUGIN-449
until that is fixed bump the plexus archiver dependency version on the maven-plugin-plugin so the warnings go away.
amends #420
=> workaround MPLUGIN-449

src/main/java/org/jenkinsci/maven/plugins/hpi/PluginWorkspaceMapImpl.java
Observed a plugin build failure
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jenkins-ci.tools:maven-hpi-plugin:3.37:test-hpl (default-test-hpl) on project the-plugin-name: Execution default-test-hpl of goal org.jenkins-ci.tools:maven-hpi-plugin:3.37:test-hpl failed: Malformed \uxxxx encoding.
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:375)
at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
at …
```
=> Handle `IllegalArgumentException` from `Properties.load`

.github/dependabot.yml, pom.xml
https://groups.google.com/g/jenkinsci-dev/c/Xua30fqoqZc
downgrade libraries and add dependabot exclusion
=> set maven libs according to consumers

src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java
Fixes #441. Tested in both Linux and Windows with a directory with spaces.
=> Support directories with spaces

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
Reverts #406. Now that BOM has dropped support for 2.332.x and 2.346.x, we can throw the exception unconditionally.
=> Drop support for 2.332.x and 2.346.x for BOM test suite

pom.xml
With the upgrade to Jetty 10, there is no longer a require upper bounds conflict with this dependency, so there is also no need to manage it at any particular version.
=> Remove unnecessary managed dependency

pom.xml, src/it/warResources/src/main/webResource-filtering/help-globalConfig.html, src/it/warResources/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java
* Filtering `webResources` now consults `System.getProperties()`  (again?)
* Filtering is now escapable so you can write `\${project.version}` and not have it replaced by the project version. (this matches Mavens' default behaviour
Replaces code from plexus-util with maven-filtering.
The code still directly uses some plexus-util so the dependency is not removed but the comment was no longer correct so that was removed.
=> fix filtering of web resources using system properties and escaping

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
I have long been annoyed at the fact that `resolve-test-dependencies` downloads one dependency at a time. This is made worse by my slow Internet connection. This PR makes it work in parallel, the same way regular Maven dependency resolution works.
Unfortunately `maven-artifact-transfer` (the nice high-level API we were using) does not support this use case. It was a very thin layer over Aether, anyway. Here we use Aether directly, which can do what we want. There is precedent for invoking Aether directly in other Maven plugins, such as `maven-enforcer-plugin`.
We do at most two "passes": one regular pass, and one (possibly skipped) fallback pass to retain the functionality of JENKINS-62658. Each pass resolves multiple artifacts in parallel for maximum performance.
This entails a bit of …
=> Resolve test dependencies in parallel

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
Extracting a userful portion of #391 that can be merged today. Tested interactively with `text-finder` and the `-X` option.
=> Log more artifact metadata in `TestDependencyMojo`

src/it/metadata-it/invoker.properties, src/it/metadata-it/plugin1/pom.xml, src/it/metadata-it/plugin1/src/main/resources/index.jelly, src/it/metadata-it/plugin2/pom.xml, src/it/metadata-it/plugin2/src/main/resources/index.jelly, src/it/metadata-it/pom.xml, src/it/metadata-it/verify.groovy
I erroneously forgot to push the latest changes to #436 at the time which mean the IT for it was still sitting on my local machine only.
Whilst [an ITs](https://github.com/jenkinsci/maven-hpi-plugin/pull/436/files#diff-0f2f097e3b673ee6c7452716ac8a8268a8a65d5c8cdf5631dc9098f9ae2518d2) was adapted there was still no IT to cover a multi-module reactor build - so this IT ensures we have coverage for that.
=> Add integration test for additional plugin manifest entries

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
For consistency with https://github.com/jenkinsci/pom/pull/419, put the Git hash in `Implementation-Build` rather than `Plugin-GitHash`. For now I am keeping it in `Plugin-GitHash` since it was (very recently) added there for PCT, but I will update PCT to start consuming `Implementation-Build` instead and plan to rip out `Plugin-GitHash` shortly (in a month or so) once it's no longer used by anything (not much is using it today, just the AWS Java SDK plugin I think).
=> Begin mini-migration from `Plugin-GitHash` to `Implementation-Build`

src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
the paths for files should not be absolute but relative.
prior to this change the war contained files like
`WEB-INF/lib/...` (all the usual entries)
and
`/WEB-INF/plugins/...` (for the bundled plugins)
fixes: #479 
IT in #480
=> Fix creation of Custom Wars

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
if the war scanning encounters a SNAPSHOT build of a plugin then then manifest file will contain a `Plugin-Version` entry like `1.2.3-4-SNAPSHOT (private abcd1234-username)`.
This causes a failure when updating the dependencies (`resolve-test-dependencies`) as the plugin will try and use that directly without stripping off the extra parts.
This strips off any extra parts should they be present so that the version number matches a valid maven version number and also emits a warning to the log about non repeatable builds if any snapshots are encountered.
manually tested with a war containing a snapshot using the command
`mvn.cmd -B -V -e -DoverrideWar=C:\workarea\myWarWithSnapshot.war -Djenkins.version=2.387.3-cb-2 -DuseUpperBounds=true …
=> Handle SNAPSHOT versions in with `overrideWar`

.github/workflows/site.yml, pom.xml
Per [this page](https://cwiki.apache.org/confluence/display/MAVEN/Maven+Ecosystem+Cleanup) Maven Wagon is deprecated. This PR eliminates use of Maven Wagon at release time, replacing it with a GitHub Action that uploads the generated site to GitHub Pages on every clean build of the main branch.
I am using this workflow successfully in Job DSL plugin. If there are any issues with this PR I will fix them after merging this PR.
Fixes #492
=> Remove use of Maven Wagon

pom.xml
Fixup to #499. Restores the mojo docs which inadvertently disappeared in that PR.
Ran `mvn -B -V -e -ntp -Pquick-build clean verify site` and verified the mojo docs were restored in the generated site.
=> Restore mojo docs

src/it/metadata-it/verify.groovy, src/it/verify-it/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
THe manifest entry was not correctly caclulated, being different depending on where you ran maven from and if you also had any local aggrgator project or not.
The original intention and need of this was to use the path from the git repostory for the PCT, but the code changed from using a git path along the way.
As a result the code produced non deterministic results and the PCT which needed this information has been updated to not need this in https://github.com/jenkinsci/plugin-compat-tester/pull/557
because the information is non deterministic and there are no consumers of this, it is simpler to remove the code.
fixes #497
=> remove Plugin-Module manifest entry

pom.xml, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestRuntimeMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
Fixes #469
Ran builds of `text-finder` (including `hpi:run`) and Jenkins core with these changes.
```[tasklist]
```
=> Migrate from `maven-artifact-transfer` to direct use of Resolver API

src/it/warResources/src/main/webResource-filtering/help-globalConfig.html, src/it/warResources/verify.groovy
This test fails for me locally on Ubuntu with the Ubuntu OpenJDK 17 package because the test relies on `java.vendor.url` being set to a URL that starts with `https://` but for some reason the Ubuntu package doesn't define a URL so this just returns "Unknown" and the test fails. By testing a different system property instead the test passes on both Eclipse Temurin and Ubuntu builds of OpenJDK.
=> Support Ubuntu version of OpenJDK in tests

Jenkinsfile, pom.xml
This change fixes https://github.com/jenkinsci/maven-hpi-plugin/issues/534 by allowing Integration Tests to execute in the context of ci.jenkins.io with its `settings.xml` mirroring setup.
This change is tested with and without a custom `settings.xml` to ensure both contributors and ci.jenkins.io environments are considered.
```[tasklist]
```
=> Restore build stability

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java
#191 did not take into account the logic from https://github.com/jenkinsci/jenkins/pull/3551.
=> [JENKINS-52665] Treat `*-SNAPSHOT` mismatches as nonfatal in `hpi:validate-hpi`

.github/workflows/site.yml
No need to deploy site on forks
Technique is working for jenkins.io and for several other repositories.
```[tasklist]
```
=> Only run GitHub actions from jenkinsci org

src/it/ensure-java-level-marker-11-migration/invoker.properties, src/it/ensure-java-level-marker-11-migration/pom.xml, src/it/ensure-java-level-marker-11-migration/verify.groovy, src/it/ensure-java-level-marker-11/invoker.properties, src/it/ensure-java-level-marker-11/pom.xml, src/it/ensure-java-level-marker-11/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/InitializeMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/extensions/HpiLifecycleMappingProvider.java
(This idea came up as a discussion during the Jenkins contributor summit, based on the IDE problems experienced during the transition between Java 8 and 11 support)
This effectively reverts #403, reinstating #323, as well as adding a new mechanism for better IDE support.
The logic of setting `maven.compiler.release` dynamically works fine for the Maven CLI. However IDE support (at least IntelliJ) doesn't work well with this and happily ignores what the plugin set dynamically. Indeed, it has its own logic to parse the pom and apply profiles, but doesn't call any maven lifecycle doing so.
Instead, it picks up the default value set through the plugin pom that defaults to the minimum java version supported (currently [11](https://github.com/jenkinsci/plugin-pom/blob/6949f8af159d30e2722fcf773b3 …
=> Generate automatically a marker file for a maven profile depending on java level to use

src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateMojo.java
See https://github.com/jenkinsci/maven-hpi-plugin/pull/582#issuecomment-1959624001; the previous fix was not tested properly and did not actually work. I tried for several hours to figure out how to update the Enforcer configuration from a different mojo but failed. Things I tried:
- Looking up the plugin from the model and munging the XML programmatically (did not work, as the `MojoExecution` object uses a different copy of the XML)
- Trying to configure Enforcer with the `enforcer.rules` Maven property (did not work, as that property does not support rules that take parameters)
- Trying to munge the XML in the Enforcer `MojoExecution` programmatically from the `validate` `MojoExecution` (could not find a Maven API to do this)
Having run out of options, I decided to skip the …
=> `EnforceBytecodeVersion` fails with "Restricted to JDK 11 yet […] contains […] targeted to JDK 17" (second try)

src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/JarMojo.java
Fixes #598
Ensured that when defining `project.build.outputTimestamp` in a plugin the JAR and JPI were created with sorted zip entries.
=> JAR and JPI creation is nondeterministic

src/test/java/org/jenkinsci/maven/plugins/hpi/TestInsertionMojoTest.java
Amends #587 to fix this test failure I got locally:
```
java.lang.AssertionError: unexpected exception type thrown; expected:<org.apache.maven.plugin.MojoExecutionException> but was:<org.apache.maven.plugin.MojoFailureException>
at org.junit.Assert.assertThrows(Assert.java:1020)
at org.junit.Assert.assertThrows(Assert.java:981)
at org.jenkinsci.maven.plugins.hpi.TestInsertionMojoTest.legalizePackageName(TestInsertionMojoTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at …
```
=> Fix test failure

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
Jetty 10:
```
jetty-server/src/main/java/org/eclipse/jetty/server/handler/ContextHandler.java
145:    public static final String MAX_FORM_CONTENT_SIZE_KEY = "org.eclipse.jetty.server.Request.maxFormContentSize";
```
Jetty 12:
```
jetty-core/jetty-server/src/main/java/org/eclipse/jetty/server/FormFields.java
42:    public static final String MAX_LENGTH_ATTRIBUTE = "org.eclipse.jetty.server.Request.maxFormContentSize";
```
As you can see, the string is the same, but now lives in `FormFields.MAX_LENGTH_ATTRIBUTE` rather than `ContextHandler.MAX_FORM_CONTENT_SIZE_KEY`.
To prepare ourselves for the transition, simplest just to inline the string so that we aren't depending on any particular calling convention.
`mvn clean install`
=> Inline `ContextHandler.MAX_FORM_CONTENT_SIZE_KEY`

src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java
This field exists two levels up the class hierarchy, so shadowing it here is pointless. It is also actively harmful, as it causes the injector to inject it in the lowest level of the class hierarchy but not in the grandparent class, causing references to it in the grandparent class (of which there currently are none, but will be in a future change I'm working on) to fail with a `NullPointerException`.
CI build
=> Stop shadowing field

src/it/metadata-it/verify.groovy, src/it/verify-it/verify.groovy, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java
Completing what was started in #471.
=> Remove deprecated `Plugin-GitHash`

pom.xml
Fixes this warning:
```
Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.
The following dependencies are in wrong scope:
* org.apache.maven:maven-settings:jar:3.8.1:compile
```
=> Fix "dependencies are in wrong scope" warning

pom.xml
Previous changes in Maven require 3.9.6 or later for Java 17 compatibility.  Fixes #667
See also
* https://github.com/jenkinsci/pom/pull/612
* https://github.com/jenkinsci/plugin-pom/pull/1018
=> Require Apache Maven 3.9.6 or later

pom.xml, src/it/override-test-dependencies-split-plugin/invoker.properties, src/it/override-test-dependencies-split-plugin/pom.xml, src/it/override-test-dependencies-split-plugin/src/main/resources/index.jelly, src/it/override-test-dependencies-split-plugin/src/test/java/sample/SampleTest.java, src/it/somedep-1/invoker.properties, src/it/somedep-1/pom.xml, src/it/somedep-1/src/main/java/io/jenkins/plugins/sample/Util.java, src/it/somedep-1/src/main/resources/index.jelly, src/it/somedep-2/invoker.properties, src/it/somedep-2/pom.xml, src/it/somedep-2/src/main/java/io/jenkins/plugins/sample/Util.java, src/it/somedep-2/src/main/resources/index.jelly, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/AbstractJenkinsManifestMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/AssembleDependenciesMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/HplMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/ListPluginDependenciesMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/MavenArtifact.java, src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/TestDependencyMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/ValidateHpiMojo.java, src/main/java/org/jenkinsci/maven/plugins/hpi/WarMojo.java
`isPlugin()` sometimes fails because the model for a dependency cannot currently be built. #104 had handled this in certain cases, but I just came across another case where https://github.com/jenkinsci/jenkins/pull/9958 meant that a dependency model could not be built because of
```
Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for org.apache.commons:commons-compress:jar is missing. @ line …, column …
```
when passing a newer `-Djenkins.version` from PCT: while `hpi:resolve-test-dependencies` worked as expected, `hpi:test-hpl` then failed because an old plugin dependency was being built against an older Jenkins core version and was picking up an implicit version of `commons-compress`.
For now, done manually using proprietary plugins; …
=> Expand robustness of `isPlugin` against unbuildable models

Jenkinsfile
This PR is another try (following https://github.com/jenkinsci/maven-hpi-plugin/pull/537) at enabling Artifact Caching Proxy ("ACP") to speed up build and contribute to the effort of decreasing bandwidth usage on repo.jenkins-ci.org Artifactory.
It tries to use the pipeline library function created since last attempts, providing a boolean feature switch in case of issue with the ACP service.
=> chore(pipeline) use Artifact Caching Proxy to speed up CI build

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
I added this line 10 years ago to address a start-up delay (#21 & https://issues.jenkins.io/browse/JENKINS-30067). However I
need now to remove it in order to allow configuration discovery.
I couldn't notice any significant delay by removing this, so I assume that
the previous delay was caused by a Jetty bug (back in 8.x) that is now
fixed in the Jetty version the Jenkins project uses.
=> Revert #21 to allow configuration discovery

pom.xml
Observed the following linkage errors when testing a plugin with a plugin-to-plugin dependency on the HttpComponents Client 4 library plugin:
```
java.lang.LinkageError: loader constraint violation: when resolving method 'void org.apache.http.impl.auth.HttpAuthenticator.<init>(org.apache.commons.logging.Log)' the class loader 'PluginClassLoader for apache-httpcomponents-client-4-api' @14163593 of the current class, org/apache/http/impl/nio/client/MainClientExec, and the class loader org.codehaus.plexus.classworlds.realm.ClassRealm @34b19c81 for the method's defining class, org/apache/http/impl/auth/HttpAuthenticator, have different Class objects for the type org/apache/commons/logging/Log used in the signature (org.apache.http.impl.nio.client.MainClientExec is in unnamed module of loader …
```
=> Linkage errors with HttpComponents Client 4 library plugin

src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java
The documentation is wrong: the HTTP [port](https://github.com/jenkinsci/maven-hpi-plugin/blob/948ffad3d078346bb5a11a561e9b437e7f40f4ed/src/main/java/org/jenkinsci/maven/plugins/hpi/RunMojo.java#L176) can be customized using `port` system property (`jetty.port` no longer works).
Confirmed that `mvn -Dport=9090 hpi:run` listens on port 9090 and that `mvn -Djetty.port=9090 hpi:run` does not listen on port 9090
=> Fix port property description in `run` mojo documentation
